version: '3'
services:
  db:
    container_name: 'db_container'
    image: mysql:8.0.23
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      # - MYSQL_DATABASE=books_api
