version: '3'
services:
  db:
    container_name: 'db-container'
    image: mysql:8.0.23
    ports:
      - 3306:3306
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
      - ./db/data/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=secret