version: '3'
services:

  service_db:
    image: mysql:8.0.29
    container_name: container_db
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306
    volumes:
      - ./database/data/:/var/lib/mysql/
  
  service_api:
    container_name: container_api
    image: node:16
    restart: always
    ports:
      - 3001:3001
    environment:
      - MYSQL_HOST=service_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=my_db
    volumes:
      - ./:/usr/api
    working_dir: /usr/api
    command: bash -c "npm run dev"
    tty: true
    stdin_open: true
    depends_on:
      - service_db